### ISSUE TITLE
Resource Page

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#10]
@TerryLequieu

There should be a way to link to resources that are not capable of being added or embedded into this app. For instance:

- [GasBuddy](https://www.gasbuddy.com/) - Save money, save time and never pay full price for gas again with a community of 70 million users. GasBuddy helps you save $340 a year by telling you exactly where and when to buy gas, and more! Use the #1 car companion app today. 
- [SwordSearcher](https://www.swordsearcher.com/) - _Windows Program_ SwordSearcher is designed by Bible Believers for Bible Believers. The primary purpose of SwordSearcher is to improve Bible study
- [eSword](http://www.e-sword.net/) - e-Sword is a feature rich and user friendly free Bible study app with everything needed to study the Bible in an enjoyable and enriching manner!
- [KJVchurches](http://www.kjvchurches.com) - an online listing of over 10,000 King James Independent Fundamental Baptist Churches worldwide. Please note that some churches may deviate from the core values of this site and we strive to note such by tagging those churches.

Please help and provide any resources you deem as important and share/use often.

**Comment by amaster507** [comment]
of course, KJVchurches will be embedded into the app, but I feel should still be listed on the resources page. These resources should be grouped together and listed by their service/subject matter.

**Comment by amaster507** [comment]
- [BRNsermons](http://www.brnsermons.com/)
- [Gospel Tracts](http://www.pocketgospeltracts.com/)

**Comment by johntink1088** [comment]
[MileIQ](https://www.mileiq.com/) - MileIQ is an automatic mileage tracker that helps you track your miles for business expenses, car insurance or maximize your tax deductions. Ditch the paper mile log in favor of convenience and greater accuracy, recording all distances down to a fraction of a mile. Log miles easily with MileIQ, the free app that automatically tracks miles every time you drive your car. With MileIQ, you don’t need to remember to fill in start and stop times on your log, and you don’t have to keep track of tons of paperwork.

**Comment by amaster507** [comment]
We should have a link to help for the app itself. This could be to a support forum or to how-to videos.
