### ISSUE TITLE
Calendar Recurring Events

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#11]
## I do not have deputation and furlough experience, so I am asking those who do:

Is there a need for recurring events at the same location?

This could be used for other personal use as well. For instance, if a missionary's home church has requested that they be home the last Sunday of every other month, they could set a recurring event/meeting/booking to be at the same place and enter the specifics for recurrence such as is available on Google Calendars.

**Comment by johntink1088** [comment]
If also used as a daily planner then yes, enable recurring events.

Quarterly reports due
Send Prayer letters.

**Comment by amaster507** [comment]
ok, then we will incorporate this as well.

**Comment by andrewwippler** [comment]
Are you building a calendar app? My input is to create is files and have them use their own calendar.

**Comment by amaster507** [comment]
@andrewwippler are you meaning .ics files? I was planning on building a calendar app, and let me explain why if it makes sense using information I read off from @johntink1088 prayer letter:

ifbmt calendar will be unique in that it will always reference the church information, notes, and map information. Bro. John told a story when he was first starting out deputation how that he traveled to the right city for a church meeting, but he had the wrong state. Totally newbie mistake, but this could happen to anyone! If ifbmt was available when John was scheduling his meetings he would have noticed on the map that one of his meetings for the month was in the wrong state. There would be no way to show this data unless a calendar was built into ifbmt. 

Another use case is that when booking meetings you can line up your route on the calendar map and then find churches in between locations to try to book as you pass through.

We can exclude the calendar from this app as it is for the community and you will be the ones using it, but I think it will be helpful and if you don't want to use it, you will not be forced to and the calendar map and calendar view can be hidden from the display very easily.

Let me know what you think.

**Comment by andrewwippler** [comment]
Yes, I meant .ics files. I was on a mobile when I posted that and it auto-corrected.

Timezones are always an issue with calendaring apps. Be careful about those :)

**Comment by amaster507** [comment]
@andrewwippler

Good point about timezones. I will open this to a new issue. I haven't thought much about that yet.

**Comment by amaster507** [comment]
@johntink1088,

Let's expand this question a little bit further still now that I am working on the database design. With events and calendars, would it be useful to have multiple calendars per user? _For instance a calendar for reporting, a calendar for birthdays, a calendar for personal bills, a calendar for hospital visits, a calendar for booked events, etc._
