### ISSUE TITLE
Dashboard Widgets/Items

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#12]
Ok, I was going to put together a dashboard view mock-up, but I stopped because I wasn't sure of what all to include on it. I need your help again, please. As this will be an app for you the missionaries, what would you like to view on the dashboard of the app? It could be very simple with just links to the other items, or I was thinking more along the lines of like a WordPress dashboard with different widgets that can be selected (and possibly arranged).  My ideas for widgets:

- Support Pie Chart
- Number of calls made in the last `X` days
- Number of Churches Considering Support
- List of next `X` meetings
- List of last `X` notes entered
- Pie chart of status of churches called in the last `X` days
- List of the `X` last publicly updated churches

`X` means insert number choice (5, 10, 15, 30, etc)

**Comment by johntink1088** [comment]
Search Bar

**Comment by amaster507** [comment]
search bar for? churches? pastors? location? notes? phone numbers? Or just global search fit all of the above plus?

the dashboard search bar should be kept simple with search results having the potential out being refined. But the question is, what all should be returned for the initial search?

**Comment by johntink1088** [comment]
Dashboard search bar should be kept simple, just church name, pastor or city.   But like you said, should have to potential to view much more, maybe from a different page
