### ISSUE TITLE
Pricing Setup and Maps API

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#13]
There is a limitation on Google map loads per day that can be used for free. [Google Maps API Pricing](https://enterprise.google.com/maps/pricing/) We will need to use the Web Google Maps JavaScript API service.

> Free up to 25,000 map loads per day

And this is only free as long as our app maintains the status of:

> Apps or websites that are free for anyone to use.

If our app ` charge[s] a subscription fee beyond the Play or App stores, [it will] require the Premium Plan.` and then the pricing varies per map loads per day.

The alternative would be to use a service such as [leafletjs](http://leafletjs.com/) which is open source and comparable to google maps.

How many map loads should we expect from a given user per day?

**Comment by amaster507** [comment]
We can word subscriptions in such a way that the service is free to use, but recurring donations will allow for further support and development.

However, if the decision is made to use Google Maps and the combined users load over 25,000 maps per day then charges will occur and most likely, we would need to change this from free to a small monthly subscription requirement.

If you review the mockups, then maps may not need to be reloaded after each church contact and notes are added as the quick cal map view would not need to be refreshed each time.

**Comment by johntink1088** [comment]
I would assume you would use a map load per call, or at least new city.  Anywhere from 20-50 per day per user.    

I'm not opposed to pay for a product that helps my ministry and improves my workflow. 

This is something geared for dep and furlough.  So after I get to field I would not need an active account until I'm preparing for a furlough.   Would I need to continue my subscription through my "inactive" stage so that all my data is stored?

**Comment by amaster507** [comment]
If we do go with a paid subscription then there would be a way to suspend your account and then reactivate.

**Comment by andrewwippler** [comment]
Have you looked into http://www.openstreetmap.org/  ?

**Comment by amaster507** [comment]
@andrewwippler welcome to ifbmt! You have some great repositories going as well...

Leafletjs actually uses openstreetmap.org framework and builds upon it. Leafletjs provides an API for OpenStreetMap.

Thank you for the information, I found out about leaflet by actually searching for an API for OpenStreetMap.

I have noticed your app 2by2. Have you implemented OpenStreetMap into that app? I haven't dived into it yet but will most definitely come back and take a keen interest in 2by2. I have thought about building a similar project!

**Comment by andrewwippler** [comment]
I have not created any maps integration. When you have an address on a prospect/contact, a link to google maps appears on the prospect. Once the user clicks the link, it takes them to Google Maps. No API required as it is not shown in the app.

For the pricing of the finished app, I can help you keep server costs low. Let me know when you have an overall idea of every service/integration you will use and I can architect it out for you. I can also help you with the build pipeline and development process if interested.

**Comment by amaster507** [comment]
@andrewwippler

Thank you so much! that is how I used Google Maps as well in openchurchadmin. I plan to start actual development on Sept 15th ish... this will give some time to get more ideas and thoughts together from the community.
