### ISSUE TITLE
Mission Apartments Lists

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#14]
I had the privilege to speak with Bob Martin from with Weekend Soulwinning Seminars last night and presented him with the ifbmt project.  He said,

# The most important thing to include is missionary apartments!

For a traveling evangelist or missionary, there is need to always find a place to stay for the night. If there was a list of churches who provide missionary and evangelist lodging that would be great! Some ministries offer multiple rooms for missionaries who are on furlough to work out of the house/apartment in between meetings.

If the community could help provide this list to incorporate with the church listings then this would be even more valuable to missionaries who are just starting out.

If you have a list then please let me know either by attaching it to this post, posting a link, or email me at anthony@amasterdesigns.com

**Comment by johntink1088** [comment]
KJVchurches has a pretty comprehensive list of PC's.   Surely there would be a way to tag them in the process of importing that list.

**Comment by amaster507** [comment]
Ok, I didn't know that Vince had those tagged. I tried searching, but didn't find them. I will be working to build an API to access his database directly.

**Comment by amaster507** [comment]
Ok, I did find the category for prophet chambers, which we will be able to scrape and make this a searchable and mappable item. I could not find a way _(but didn't spend much time on it either)_ to search for the nearest prophet chamber to your location, or in a specific area. This would be helpful if you know you will be traveling through and need a place to stay in a general vicinity.

**Comment by MC1171611** [comment]
The tags are searchable through the main search; eg. "prophets chamber" in the left box and "75050" in the right box (my home church has a missions house). I don't know how that would be implemented through in the app, but that information is available and is tied to the church's listing.

**Comment by amaster507** [comment]
@MC1171611 Welcome to ifbmt!

I did find the tag and the URL that lists all of the churches with prophet chambers. I think the best way to implement this would be to use a filter in the right-hand panel when searching for churches.
