### ISSUE TITLE
Missionary/Ministry finder for churches and pastors

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#16]
When a pastor is in search of a missionary to support or that would be available to come to a Missions Conference, Camp Meeting, etc. they sometimes will refer from other pastors. What if a pastor or church is looking to support a missionary in a field that they do not currently support? How do they find a missionary?

OK, I know all of these situations may be very hypothetical and may not ever happen like that, or do they? What if there was a way a pastor could have an account on this app to allow him to easily find a missionary?

I understand that some missionaries may not want this feature, so this would need to be an opt-in feature only. But is this something that is even wanted? Do pastors ever reach out to missionaries and make the first contact? If so, how do they find the missionary? 

_Excuse me for this next question, just my thoughts spinning:_ Would a missionary rating system be useful for pastors to help each other out in recommending missionaries?

This might also give churches/pastors a reason to help us keep their own information up to date. I try to find a 'reward for use' for everyone who might be contributing data.

From the church staff view, there are some missionaries who 'shoot themselves in the foot' while at the church and will not get support from the church. What if there was a way for the app to send a 'survey' to the church/pastor for them to be able to rate the missionaries experience at the church and highlight the positives and give insight that they saw that could have been better. _Again maybe something that some people might find offensive, but just my thoughts._

**Comment by sdwire** [comment]
I'm also working on a system much like you're describing here. Part of that process for me was a deputation survey designed to help me better understand the needs of both missionaries and pastors during the deputation process. I specifically asked about both missionaries' and pastors' comfort level on a rating system. In the responses from 350 pastors and 375 missionaries, any feedback that was remotely positive on the idea seemed to still be skeptical. A great deal of feedback was vocally against the concept of any "yelp-style rating" (as one respondent put it) of missionaries or churches.

I'll be publishing the results of that survey and sharing the report with everyone who took it. amaster507, ping me at sdwire@edifyhub.com if you'd like a copy, or if you'd like to chat further on where our research and ideas may overlap.

**Comment by amaster507** [comment]
@sdwire welcome to ifbmt!

OK, I was sort of hesitant to even put that comment on there if you could read into my post. Thank you so very much for your information!

So how about if we tone this down to just a listing of missionaries with no rating scale. Just a simple way to make the users information public and a way to search for and send a message to the missionary.

**Comment by sdwire** [comment]
@amaster507 you said, "This might also give churches/pastors a reason to help us keep their own information up to date. I try to find a 'reward for use' for everyone who might be contributing data." That's a big point right there. Many IFB churches don't keep their own websites up to date, let alone sharing changes with others on the outside. And the reasons that's true aren't necessarily bad reasons; it's just our difficult reality.

**Comment by rmurray525** [comment]
I agree, most churches do not keep their info up on their own site. Then you also have the problem of all the other sites that are outdated. 

I think letting the missionaries update is the thing. As they call, they make notes of a number that didn't work etc.... then another missionary finds a good number and can fix the bad one. All working together. 

I also don't like the rating system. I think it would make us too competitive and possibly bitter at one that got a bad review. I think a lot of pastors have certain boards they like and trust. If they need a missionary, they would look to those boards via calling or website. 

However, on the survey idea, what about a survey for helping the missionary?  Something we could send the pastor to fill out and tell what he did or didn't like so the missionary can improve his process for the next church? It could be an option for the missionary. This may be getting into too much... basics first, right?

**Comment by amaster507** [comment]
Yes, there will definately be a way for users to mark numbers/emails/addresses as invalid which sets an alert on the contact for others to help resolve. Please see issue #5

**Comment by jrwilliams27** [comment]
Our mission board has us send a survey after every meeting while on deputation years ago. The feedback that caused them to stop using the surveys was very similar: pastors and churches asked why our mission board did not trust their missionaries, and needed a survey to keep track of what they were doing. 

I know this is different as the app is not a mission board, but I think the sentiment would be similar.

**Comment by amaster507** [comment]
From the comments received, We will be holding off on this matter for the time being. We might revisit this as @rmurray525 added as an optional tasks, but let's get the basics going first.
