### ISSUE TITLE
Church listings overview data

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#17]
Referring to the following MockUp:

![MockUp Quick Cal and Church Listings](http://amasterdesigns.com/wp-content/uploads/mock-up_quick-cal_and_church-listings.png)

What information would you want to be listed in this view? 

- Church Name
- Church Address
- Pastors Name
- Church tags
- Personal status with the church (ie: booked, supported, do not call, left voicemail, etc)

I was thinking some of the information could be represented using icons. such as:

- The red announcement for high priority public notes
- The yellow exclamation for extremely low/negative public notes
- A blue question mark requested/pending updated information
- Green dollar sign for support already received
- Black dollar sign for support promised but not yet received
- etc.

**Comment by sdwire** [comment]
My detailed analysis is at home, but eyeballing the responses to my 2017 deputation survey, here is the church information missionaries rated most valuable (of the elements that I asked about):

- Pastor's name
- Pastor's email address
- Church office email address
- Bible translation philosophy

What surprised me most was how low an importance they gave to an exterior photo of the church. I would have expected that to be valuable to help them make sure they found it, but it was consistently rated as not very important.

I can share more concrete numbers around missionaries' value rankings of church information when I get home tonight.

**Comment by amaster507** [comment]
@sdwire Wow, your data is so great!!

- [x] Pastor's name
- [ ] Pastor's email address `will add`
- [ ] Church office email address `will add`
- [x] Bible translation philosophy `seen as tags`

Seeing this, we will need a way to distinguish between church's contact information and pastor's contact information. I don't believe this distinction is currently available with data from sites that I scraped the data from.

**Comment by sdwire** [comment]
Here's a relevant sample of the kind of data I was able to collect in my survey. It shows the distribution of answers as missionaries ranked from 1-10 how valuable each piece of information is to them during deputation:

* Name of pastor
* Age of church
* Average attendance
* Number of supported missionaries
* Typical missionary support level
* Pastor's seminary or Bible college
* Pastor's email address
* Pastor's social media addresses
* Church office email address
* Church social media addresses
* Bible translation philosophy
* Music philosophy
* Interior photo of the church
* Exterior photo of the church
* Pastor's opinion of your presentation

Graph is ordered with least important on the left, most important on the right.

![screen shot 2017-09-05 at 9 32 19 pm](https://user-images.githubusercontent.com/11800061/30090645-c29a40b4-9282-11e7-985b-334e5785ea5f.png)

**Comment by amaster507** [comment]
Wow! I LOVE that data representation. This information is priceless. It is odd how pastors opinion ranked 4th overall above even Bible translation and social media links, but that there was still mostly a bad taste when it came to a ranking/review setup.

**Comment by sdwire** [comment]
The rest of the data and comments from the survey do help explain the difference between the desire to know the pastor's opinion and the distaste for ranking/review. I don't have that data crunched for presentation yet, though.

It's also interesting to see how polarizing the Bible Translation issue is. It got noticeably more 10s than Pastor's Opinion (which ranked higher), but also noticeably more 1s, 2s, and 3s. Lots of 7s and 8s on Pastor's Opinion helped raise its average above that of Bible Translation philosophy.

Social Media accounts also seem a bit polarizing, with more concentration on the extremes in both 1s and 10s than their neighbors have. Some of the other survey questions give some hints on that, though I haven't finished the analysis on it.

**Comment by rmurray525** [comment]
I think it important to add phone numbers. Possibly the pastor's or maybe the pastors preferred. Honestly, I have had little to no success calling an office phone. many churches do not have staff or other people there during the day.

**Comment by sdwire** [comment]
Phone numbers are both a gold mine and a land mine.

For some pastors, a direct phone call is the best way to make a real connection. For others, if you cold contact them by phone without going through the office "filter", you've destroyed any chance of a relationship.  I haven't yet distilled the details on this, but - on the surface - phone contact appears to be a seriously polarized issue for pastors.

**Comment by amaster507** [comment]
This could help be handled by users adding public notes for the specific ministry. If someone calls the ministry and then finds out that the pastor would have rathered the person call the office then a public not can be added stating such.

**Comment by rmurray525** [comment]
Agreed. 
If users make edits like that in it as they use it, that helps the next person not make the same mistake.
