### ISSUE TITLE
Calendar and timezones

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#18]
The issue of timezones was brought up by @andrewwippler when tagging the calendar Orion of the app.

Here is my thoughts for this process:

- Enable users in the setup condiguration and profile settings to select and change their timezone.
- possibly allow a quick change of the timezone setting when traveling. This change will not be automattic bit like a quick link to change on the fly when needed.
- store all bookings, notes and events in UTC and then display according to the setting chosen at the time.
- when viewing church details there can be a notice that they are in a different timezone.
- when booking the meeting the time will be saved as UTC offset by the churches local time.

Let me know if your thoughts and suggestions for this.process.

**Comment by andrewwippler** [comment]
> store all bookings, notes and events in UTC and then display according to the setting chosen at the time.

conflicts with

> when booking the meeting the time will be saved as UTC offset by the churches local time.

You will want most of the timezone calculations on the save aspect and not on the retrieve. If you sanitize all timezone data (i.e converting it to `Z+00:00` before save) it makes it that much easier on the presentation layer - you can assume the data you are retrieving is already UTC.

**Comment by amaster507** [comment]
@andrewwippler so I did not make my thoughts very clear there obviously, I apologize. When booking the meeting and the meeting is at say 6:00 PM and the user is in CDT (UTC-5) and the church is in EDT (UTC-4) then the meeting would be saved as 6:00 - 4 to save the EDT as UTC. And when adding a note the timestamp would be saved as the current UTC time.

Basically yes to what you said:

> You will want most of the timezone calculations on the save aspect and not on the retrieve. If you sanitize all timezone data (i.e converting it to Z+00:00 before save) it makes it that much easier on the presentation layer - you can assume the data you are retrieving is already UTC.

**Comment by amaster507** [comment]
This comment will be more for my technical reference:

All of the churches are saved in the database and have a latitude and longitude. What is needed is to also store additional timezone information such as:

Field | Description
-- | --
zoneName | The time zone name.
abbreviation | Abbreviation of the time zone.
gmtOffset | The time offset in seconds based on UTC time.
dst | Whether Daylight Saving Time (DST) is used. Either 0 (No) or 1 (Yes).
dstStart | The Unix time in UTC when current time zone start.
dstEnd | The Unix time in UTC when current time zone end.

This information can be obtained from:

- [Google TimeZone API](https://developers.google.com/maps/documentation/timezone/) or
- [TimeZoneDB API](http://timezonedb.com/api)

I believe that TimeZoneDB appears easier to use and implement. The only drawback is that requests are throttled to 1ps, but this should not be an issue because this would only need to pull the information once per location and then save it in the database when needed next time.

**Comment by amaster507** [comment]
added to roadmap https://trello.com/c/YwRODhPw/27-timezones
