### ISSUE TITLE
Mass emailer

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#19]
What if there was a way to refine a search list of churches and then send an email to all if then at once? 

This may need to be reviewed or limited in use to not cause spam. We don't want this to end up being something that every preacher/church ignores because it is overused.

**Comment by rmurray525** [comment]
IMO it would need to push as the missionary and not the app/system. It would become ignored if not.

**Comment by amaster507** [comment]
@rmurray525  Welcome to ifbmt!

If we go ahead with building am email client into this app then every user would receive a unique emaill adress in the app such as anthony.master@ifbmt.com

**Comment by rmurray525** [comment]
Exactly, which is when I fear them starting to ignore it or getting hit as spam. 
Of course, if it got built into the system, I guess it would be an option for the user to use or not use. 

I would not use it as I think it looks more professional for mine to be @reachingbolivia.com. Others might not care though.

**Comment by rmurray525** [comment]
By the way, thanks for the welcome. I love the idea. I greatly needed something like this for deputation. Wouldn't hurt to have it now for furlough.

**Comment by amaster507** [comment]
closing per comments not really workable/needed. Would be treated as spam.
