### ISSUE TITLE
Require Paid Subscription SAAS?

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#23]
OK, so I have some support and recommendation to market this as a paid SAAS (Software As A Service) application. There are many benefits to this as well as draw backs. Let's hear your thoughts and feedback.

How much would you pay for a service application like this?

With regards to #22 User Points, should the costs decrease with the more points a user obtains? This would give a financial benefit to help keep the information up to date and upvote suggested edits and public notes that were beneficial.

What should be done with the money that is received from subscribers? I know myself and others would like to be compensated for our time and effort, but how should this be done? Who should be responsible for the accounting aspect?

**Comment by rmurray525** [comment]
Personally, I would be more likely to pay for this as a one time fee rather than any monthly fee.  Even if said fee was a little large, I would rather pay up front than to pay monthly.  Especially since you have the issue of once the missionary goes to the field, they dont need it during that time.  I wouldnt want to pay for this while gone as I wouldnt be using it.  However, I also wouldnt want to start over from 0 on any points system, and personal notes/info.

Personally, if it was pushed by a mission board or highly recommended by other missionaries, I would pay as much as $100. More if it also supported some desktop version (maybe online). That seems very high to some.  However, with the work behind it, the tools it would provide, it worth be worth that to me as a "tool of the trade".

If that does not work in the long run for those working, maybe a smaller amount per year and get any newer builds.  So, maybe pay $25 for 1yr, I keep my account and records (with no end), receive any updates during said year and such.  Then if I want the newer version, while I am on my next furlough, I pay $25 for the newer version. Over time, this would probably create more sustainable revenue than the one time fee.

I could also see mission boards possibly wanting some type of group rate.  Maybe group accounts that store board supporting churches specifically for their missionaries.

**Comment by amaster507** [comment]
As mentioned in #13 if we do go with a paid subscription, there would be a way to pause the subscription and pick up exactly where you left off. No points would be lost and all of your notes and calendar events would be there as soon as you reactivate.

>  More if it also supported some desktop version (maybe online). That seems very high to some.

This application will be web based online and will be accessible from almost any online connected device (i.e. smart phone, tablet, laptop, desktop). It will be designed to work with almost every operating system (Android, iOS, Mac, Windows, Chromium).

**Comment by johntink1088** [comment]
If it is a subscription it needs to be on an annual or bi-annual basis.    But I personally would rather a one and done fee.  But I guess it all depends on what the overhead is. 

The $ that comes to my mind would, if this does all that we are expecting would be in the $25-$40 a year. Or $100-$150 one and done.   Is that too low?  

I'm saying this already having 50% support and love offerings coming in.  Just starting out on deputation you barely have money for fuel.

**Comment by amaster507** [comment]
### +1 if you agree or comment to suggest modification please.

I have been doing some research and prayerful contemplation about how to best price and market ifbmt. An article I recently found helpful is [SAAS Pricing Models](https://www.cobloom.com/blog/saas-pricing-models). There are a lot of good truths in this article about pricing models, strategies, and tactics. I propose a new custom model that includes a little bit of everything but keeping it super simple.

For comparison I found remotely similar online applications _but these services do not sync public data between accounts or offer >10,000 IFB churches upon sign-up_:
- **[DonorElf](https://donorelf.com/)** - "_helps missionaries easily keep tabs on their support account and ministry partners._" Features contact management and support tracking. **$17.95/mo.**
- **[Denari](https://denarisoft.com/pricing/)** - "_for organizations who manage support for multiple personnel and missionary names._" Features missionary management and support tracking and contact management, usually used by mission boards with abilities for missionaries to log in to view data. **$200 startup costs and $79/mo. for 500 names**
- **[SalesForce NPSP](http://www.salesforce.org/nonprofit_product/nonprofit-editions-pricing/)** - "_a single, unified view of every interaction with clients, supporters, members, funders, volunteers, and affiliates._" Features contact management, support management, affiliate management **$36/mo billed annually**

As missionaries starting out may not even have enough money for fuel, some may not be able to afford a large upfront cost, however, there are some that have worked and have a savings account when starting deputation and have a large backing to start deputation so the ends of the spectrum vary greatly. **There is a need to a simple low cost start up** and a need to **pay it once and forget it**. On initial sign up of a user, there are extra processes that go to create the actual account. This includes creating a private database for private data such as notes, events, and contacts. This work will mostly be automated by a signup script, but this does involve some extra resources. This application needs to be kept strictly to IFB missionaries as to not corrupt the public data set. As users will earn points based on a scale #22  the point system can also reward the user for actively contributing updates for churches and public contacts. The sign-up cost will help keep the everyday non-missionary from signing up for the app just to see what it is. (I think most of us have been there.) I propose the following pricing model:

## Proposed Pricing Model
- **Trial** lasting for 60 Days costing **$7**
- **Monthly*** recurring charges billed automatically every month **$12**
- **Quarterly*** recurring charges billed 4 times a year **$33** (_>8% savings_)
- **Bi-annual*** recurring charges billed twice a year **$62** (_>13% savings_)
- **Annual*** recurring charges every year **$107** (_>25% savings_)
- **Lifetime** pay once and forget it **$137** (_less than annual cost on monthly plan_)

_*For all recurring plans, account can be suspended to stop charges and then can be reactivated at any time to pick your same data up right where you left off._

The simplicity is in the sign-up process and displaying the prices. If you have ever created an Askimet account then you are familiar with sliding pricing. There is a slider with a dollar figure on top and a description below. As you move the slider to the next point the amount and description changes. This will be much easier for the user to see how paying more actually saves them in the long run, but that they are welcome to sign-up for as little as $7.

## Askimet Example
![askimet](https://user-images.githubusercontent.com/2472115/30307505-2ffa64a2-9744-11e7-990c-c2f962919838.jpg)

**Comment by amaster507** [comment]
I want to award those who have helped and those who contribute to the development of **ifbmt**. If you have or do provide input and feedback of any kind during development, then I want to reward you with an automatic lifetime license to ifbmt!

Also if you read #22, you will see awarded points for referring users to ifbmt or simply adding public notes or suggesting edits to churches or public contacts. For every 500 points you earn you will receive one free month of service.

**Comment by amaster507** [comment]
@rmurray525 

> I could also see mission boards possibly wanting some type of group rate. Maybe group accounts that store board supporting churches specifically for their missionaries.

Per #24, I am getting ready to send out a mass email to mission boards, colleges, and other mission minded ministries to promote ifbmt. I will be presenting the project to them for promotion among their missionaries and will be asking them for feedback and input in the development process. I will include this possibility of use on their side as well as discounts that will be available to their missionaries.

**Comment by amaster507** [comment]
done
