### ISSUE TITLE
User Authentication with Social Media Sites

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#25]
It is possible to integrate social media user authentication for the sign up and log in processes. This I believe would be helpful for the many people such as myself who simply have too many usernames and passwords to keep track of. This can be done using the [Hybridauth PHP Library](https://hybridauth.github.io/). There is even a possibility to load contacts from some of the authentication sites. Please see this list below:

- Facebook*
- Twitter*
- Google*
- GitHub
- Reddit
- BitBucket
- WordPress
- Tumblr*
- Disqus
- Dribbble
- WindowsLive*
- Foursquare*
- Instagram
- LinkedIn
- Yahoo
- Odnoklassniki
- StackExchange
- OpenID
- PaypalOpenID
- StackExchangeOpenID
- YahooOpenID
- AOLOpenID
- Steam
- Discord
- TwitchTV

_*Possibility to load contacts_

**Comment by amaster507** [comment]
For my reference, a tutorial example of implementing Hybridauth: https://www.sitepoint.com/social-logins-php-hybridauth/

**Comment by johntink1088** [comment]
It would be handy to have my facebook and twitter contacts linked.  I like the idea of this.

**Comment by amaster507** [comment]
This will be implemented towards the latter part of development.

**Comment by amaster507** [comment]
added to the roadmap https://trello.com/c/rM1cwLpd/25-third-party-integration
