### ISSUE TITLE
Contact Management

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#26]
As not all contacts will be associated with churches, there needs to be a way to manage contacts separately from churches. _(For example, you might have personal acquaintances that you meet along the way and are supportive of your ministry or even help fulfill needs that you have but are not members of a local church.)_

Some churches might have multiple contacts and some contacts might not have any assigned church as I perceive it. I personally do not see the need for a contact to have multiple churches, but this can be setup if it is needed. **Let's hear some feedback.**

A new contact can be created by a few different processes:

1. A church is loaded in the main view and a new contact is added to the displayed church.
2. The contact screen is loaded and the add new contact icon is pressed. While creating this contact there is an option to add home church to the contact being created using a simple search form and drop-down list
3. Contacts can be loaded from your connected Social Media Account if supported. See #25 
4. Contacts can be imported from a file. See #8 
5. Contacts can be received from other users who share them with you. 
    - Shared contacts will sync updated information
    - But will not share private notes
    - Public notes on personal contacts will be public only for the users that the contact was shared with
    - Only the owner of a shared private contact can switch the contact to a public contact. A received shared contact cannot be switched to a public contact.

**Comment by amaster507** [comment]
When data is pulled from initial data scraped from other sites the pastor information could be saved as a public contact. I think this would also help for when pastors change churches. The pastor's contact is simply linked to a different church instead of being duplicated over again.

This would also help in regards to #17 with the distinction between church contact and pastors contact. All contact information would initially be loaded as church contact and then users can update or migrate contact information from the church to the pastor if it is his personal contact information.

**Comment by rmurray525** [comment]
Having pastors separated like that would be helpful in the idea that you don't lose the personal contact info.  That would be very valuable to the next missionary.

However, would it possibly cause a lot of duplicating in the idea of those that don't know the pastor was originally in the system?  For instance, I untag  a pastor from church xyz.  Another missionary finds the same man is now the pastor of church zyx, don't know he is in the system and duplicates him to add the "new" pastor he found.

**Comment by amaster507** [comment]
@rmurray525 I have actually ran into this in my openchurchadmin project. We would have a 'visitor' that would get re-added to the system and then when adding giving records we would have disjointed records.

We solved this by suggested existing people when adding a new person. We could implement suggested public contacts for new and existing contacts.
