### ISSUE TITLE
Ability to have Multiple Calendars per User?

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#28]
From #11: (opened to a separate issue.)

> Now that I am working on the database design. With events and calendars, would it be useful to have multiple calendars per user? For instance a calendar for reporting, a calendar for birthdays, a calendar for personal bills, a calendar for hospital visits, a calendar for booked events, etc.

There could then be a user option for what calendars to show by default and the option on the calendar when opened in the Main Menu Panel to filter based upon calendars events are on.

I think this would be helpful for missionaries as they schedule everything on a calendar in ifbmt instead of keeping separate calendars.

A Birthday calendar could easily be generated with birthdays from every private and shared contact.

Imported calendars could be kept separate by having their own calendar and events could be moved from calendar to calendar.

**Comment by johntink1088** [comment]
I can see the advantages of this.
