### ISSUE TITLE
Needed? Sharing Private Contacts without going Public

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#30]
One of the proposed benefits of ifbmt is:

[Wiki: Benefits](https://github.com/amaster507/ifbmt/wiki#benefits)
> Add personal contacts that can be saved privately and shared with others globally or individually

I want to focus this issue on the actual benefit and usage of sharing private contacts individually. How this could be done is when creating a contact you choose to create the contact privately and then later on decide to share it with another user on the ifbmt app. This could be done without putting the contact into the public for ALL users of ifbmt.

## Question:
Is this a function that you would use or see a benefit of having?

## Reasoning of asking:
This functionality is presenting to be somewhat difficult (not impossible) to create. See Technical Database Design: #29. It would save development time and resources if this feature was left out. But, if it is really needed and wanted then please reply and make known your thoughts and we can continue with including this feature.

**Comment by johntink1088** [comment]
I see no need for this personally.   If I wanted/needed to share a contact with someone it would most likely be through email or SMS.  And on the flip side if someone shared a contact with me I would prefer it through SMS or email so that I could save it directly to my phone/tablet.
