### ISSUE TITLE
Churches and Pastors updating/removing their contact info

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#31]
From Chris Yetzer:

> Allow pastors or churches to update their information or remove their numbers.  As a missionary I don't like it, but some pastors don't want to have their cell phone number made known to all missionaries.  If a missionary puts that number on the app, accidentally or otherwise, there should be a way a pastor could remove it or ask that it be removed.

**Comment by amaster507** [comment]
There could be several different ways to implement this process. My thoughts on how to do this would be to have this function as a separate form on the public ifbmt.com (_coming soon_) website. I know we have discussed this issue somewhat in #26, and suggested using public notes to indicate a pastor or church may not want to be contacted via a particular method. But we did not discuss for a way for a church or pastor to ask to remove their personal information from being public to app subscribers.

This brings up a related question in my mind, When contacting a church or pastor that does not have their contact information publicly available, do they tend to ask where you got their contact information from? Why I ask this question is because, how would the church or pastor even know that their information is public to subscribers on ifbmt and that they even have a option to possibly request their information be concealed?

**Comment by MC1171611** [comment]
I've had some churches ask where I got their information, but it's rare. That being said, we could always add a radio button or toggle on the back-end of KJV Churches to prevent the listing from being loaded in the app.

**Comment by amaster507** [comment]
@MC1171611 do you think the best way to collect this request for removing their contact would be to add a form to kjvchurches.com?

**Comment by MC1171611** [comment]
@amaster507 The best way would probably be a note/request within the standard update form. I don't want to encourage the removal of listings on KJV Churches, and I don't particularly want the two projects obviously or publicly connected.

**Comment by amaster507** [comment]
Of course not remove listings, just a way to remove a contact number if it is a personal number.

Why don't you want the two projects connected when they would be in a way? Wouldn't it be helpful to promote your website?

**Comment by MC1171611** [comment]
It would do more harm than good. Pastors won't like the idea of their information being available to missionaries, and would be less likely to help with the updating of the data.

**Comment by rmurray525** [comment]
I will say that as a user, I think it would be good.i stopped using the website because so much of the data was out of date. I have 1 supporting church that has a Pastor referenced from about 10yrs ago. They have had 2 pastors since then. 
With the app, partnered to it, it would be much more up to date over time.

**Comment by amaster507** [comment]
@rmurray525 My stance to linking with the formerly announced website has been changed. I have been asked to not publicly or obviously relate the two sites together.

I have a database of all the churches and will keep our data separated from the other  site. Some of the information will be out of datE and can be updated by users suggesting edits to public contacts and churches and then they are peered reviewed for validity. Once three users with enough reputation points confirm the edit then it is published in ifbmt as the actual information instead of just a suggested edit for all to see. If you have not yet please review #22 User Rights and Privileges.

**Comment by MC1171611** [comment]
@amaster507 I think you misunderstand what I'm saying. I don't want to make it public that "IFBMT data comes from KJV Churches." That's all I'm saying.

**Comment by amaster507** [comment]
@MC1171611 you do know that what you just posted IS public on the World Wide Web correct?

**Comment by MC1171611** [comment]
Yes, brother. I know how the Internet works.

**Comment by amaster507** [comment]
There will be a general contact form on ifbmt.info for non users to post questions, suggestions, and ask for assistance such as make contact info private. There will be no relationship to MC1171611 site at all.
