### ISSUE TITLE
Beta Testers Needed

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#35]
I have the church database built and ready. I have started development on the User Interface and should be ready to start testing soon. Testing will take place in several phases. I am looking for help to simply use the application on different devices to give feedback as to what works well and what might need some adjustment.

1. **Phase 1**: _Church Listing, Sorting, Filtering, and Searching._ This stage will have access to the church database and allow users to quickly find church listings. At this stage there will not be implementation yet to suggest edits or add notes, just simply finding church listings.
2. **Phase 2**: _Contact Listing, Sorting, Filtering, and Searching._ Very similar to phase 1, but for contacts instead of churches. At this stage contacts will be linked to churches and churches will be linked to contacts.
3. **Phase 3**: _Private and Public Notes._ This stage will give users access to add private and public notes to contacts and churches.
4. **Phase 4**: _Calendar and Event Bookings._ This stage will give users access to add calendar events and book church meetings.
5. **Phase 5**: _Maps._ This stage will bring all churches and calendar events to a map view. Churches can be located on a map and items on the map can be filtered.
6. **Phase 6**: _Suggested Edits and User Points._ This stage will allow users to suggest and confirm suggested edits to churches, public contacts, and public events. 
7. **Phase 7**: _Support Functionality._ This stage will allow users to track financial support from churches and contacts.
8. **Phase 8**: _T.B.A._ To Be Announced

I will be creating a beta tester registration form soon on ifbmt.info to register as a beta tester to use the application as it is being developed. Any information in the beta application will be transferred as best as possible to the live application once it is launched. There may be some lost information though as some bugs will still need to be worked out.

## In the mean time, if you are interested in becoming a beta tester for ifbmt then please comment on this issue.

**Comment by rmurray525** [comment]
I would love to test it. I use all iOS devices (looking hard at Android though). 
I am finishing furlough soon so may not be a whole lot of help but I would love to do what I can.

**Comment by amaster507** [comment]
Beta Testing for Phase 1 is now ready! Please email me at anthony@ifbmt.info so I can setup your account and direct you how to access the web application.

**Comment by amaster507** [comment]
@rmurray525 Please email me so I can setup your testing account. I need your name, email, sending church, and either field or ministry.

**Comment by amaster507** [comment]
no need for beta testing. The app is now live.
