### ISSUE TITLE
Call Log with Reminders

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#38]
@jrwilliams27
A feature that would be very useful would be a way to record a call/contact log for calls/emails/contact to a church - apart from the notes or integrated into the notes. The date/time could be automatically recorded (or changed), a note made, and a scheduled time to contact the church again could be made. A reminder option could give options to notify at a certain date/time, and then when that time is due, the reminder notifies you of the contact(s) needed to be made, filter out the contact(s), that list would be generated, and then one can work through the contact(s).

**Comment by amaster507** [comment]
I like this idea. Almost like a self-created/assigned tasks list. Device notifications will be something that I will need to look into and learn more about for the reminders to actually send out a notification. This could be done with email and define a certain time frame between emails to aggregate the reminders together to prevent being overloaded with emails or notifications. For my professional job, I handle OnStar leads for customers needing service work who have signed up to be notified and this lead management system works in much the same way as you describe.

I think that instead of filtering out the main contact list have a new list of "Call Log Reminders" or "Task List" (whatever the name may be) to show just the ones that need to be recontacted in the order that they were set to be reminded. In my thoughts I perceive this to look and function like the "Recent Contacts" list on the left view menu.

**Comment by jrwilliams27** [comment]
Exactly. I use this with another app at the moment, and it is something that has been my go to place.

**Comment by amaster507** [comment]
done
