### ISSUE TITLE
Ideas and Vision

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#4]
@hometeamsmissions

I am thinking of a missionary making calls for meetings and being able to tap the phone number to call from a phone, while having it open on a tablet or PC and with the ability to type notes on the call or create a calendar item for a scheduled meeting.

**Comment by johntink1088** [comment]
Thinking with a spreadsheet set up in mind, have an open column for notes, as well as columns for calendar (auto-sync), date called, and call responses.

**Comment by amaster507** [comment]
Framework7 actually allows for multiple panels being opened simultaneously on larger format devices and sliding panels for smaller format devices. It works really well and have used it before. For instance a right side panel could have notes and left side panel could have calendar view/map.

**Comment by amaster507** [comment]
I am working on a mock-up for this view to help explain how I envision this to work.

**Comment by amaster507** [comment]
See the wiki page for [mock-ups](https://github.com/amaster507/ifbmt/wiki/Mock-Ups). More coming soon!

**Comment by andrewwippler** [comment]
On a device that can make calls, I believe it opens the phone app for <a href="tel:+1 (123) 123-1234">

**Comment by andrewwippler** [comment]
On a device that can make calls, I believe it opens the phone app for `<a href="tel:+1 (123) 123-1234">`

**Comment by amaster507** [comment]
@andrewwippler yes that will definitely be possible. [Google Click to Call](https://developers.google.com/web/fundamentals/native-hardware/click-to-call/)

But what if, you could be on your tablet or desktop with your phone laying on your desk and you click to call and your phone rings and it also rings the other number as well. This would be really helpful if you were using Bluetooth as well. No longer would you need to look up the phone number on your desktop/tablet and then type it into your phone to call, and possibly mistype it, _I'm sure that's never been done before_.

If this is the feature that was thought about, then what kind of phones are we using, mainly androids, and iPhones? or is there some Windows Phones out there as well? We will try to support as most as we can with a feature like this that may be dependant on another app or feature only available on select operating systems.

**Comment by andrewwippler** [comment]
An easy way to accomplish this is to SMS the phone with the text:
`send from <app>: Call <name> +1 (123) 123-1234` 

Then the user could click the link in the SMS.

Another method is to have an app installed on the phone and using a service like push bullet. (Building push bullet manually would require a Messaging Queue like NATS.IO, ActiveMQ, ZeroMQ, or the like.)

**Comment by amaster507** [comment]
@andrewwippler

Great idea with SMS! I tend to make things more complicated.

**Comment by benkennedy13** [comment]
Just to throw this out there since you are talking integration between computer and phone as separate devices. At present Android has 88% of the market share. So I'd develop toward that and I believe AirDroid has a feature called handoff. That could be leveraged to allow a hand off between PC and phone, without requiring additional steps such as the SMS intermediary. This would allow you to achieve your initial thought Anthony and be working within the application on your tablet and drop a call to your phone. With that said, I see that you have referenced Framework7. You might consider a native app instead of web or hybrid. It opens up more doors to integration. More food for thought, I suppose.
