### ISSUE TITLE
Sending Updates back to Site Scraped From

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#5]
The problem with these kinds of tools is the database. For the tool to be useful the database has to be kept current. If enough missionaries are involved, maybe a simple form for correction as a pastor changes, a church closes down, or a prophet's chamber is built could help with the capture of that information. We could gain manpower in keeping it current if they had some access to make updates as they are making the call or on site. ~~NameRemoved~~ is an awesome tool. I'm not sure how updates are going except that I know who to contact if I notice something wrong.

**Comment by johntink1088** [comment]
There would need to be some sort of verification process as changes are made or suggested.  Maybe have 2-3 admins that could fact check and approve/disprove.

**Comment by amaster507** [comment]
Definitely, excellent idea. I had this in mind but had not wrote it down yet. thank you for this.

I was thinking of having a way to track confirmed edits and then once a user reaches a certain approved edits without any denied edits their following edits would require less approval or even be automatic. This would give almost like a privilege system like stackoverflow.com works. Earning points and the higher points a user has the more editing capabilities they have.

And of course a way to track edits in case it was made in error that way data is not lost.

**Comment by MC1171611** [comment]
Basically all updates should go to ~~EmailAddressRemoved~~ and I'll make the updates. Whenever an update comes in, I don't just change the affected information: I overhaul the entire listing, especially if it's old. While that would make the process a little longer, and the updated information wouldn't be _immediately_ available, it does allow for better QC for the data.

**Comment by amaster507** [comment]
@MC1171611 you realize that there could be potentially hundreds of these updates coming in every day. Are you sure you want to handle all of the work in this manner? If this is what you want, then I have no problem setting it up that way, I just don't want to overload you when the process could be automated with check and balances.

**Comment by MC1171611** [comment]
It will end my eternal updating process, and I simply don't trust that user-submitted updates would follow the proper form, so I'll just take care of it myself. 

A way to add missing church listings would also be helpful, as in updates not connected to an existing listing.

**Comment by amaster507** [comment]
OK, just so you know though any kind of data validation needed can be built into ifbmt, but ~~NameRemoved~~ is your baby, so however you want to handle that...

> A way to add missing church listings would also be helpful, as in updates not connected to an existing listing.

So a user on ifbmt adds a church that does not cross reference to ~~NameRemoved~~ How would you like to handle that? Data validation and then added as a draft church in ~~NameRemoved~~ for you to review? All of that could be done with a custom API.

**Comment by MC1171611** [comment]
A draft would be one way to do it. However, that would require another form which would need to be pretty complex for all the data that's involved. 

My initial idea would be a red "Update" button or something that would present the user with a text box to submit updated information. That would create an email linking the user and listing ID (WP post ID), and allowing for the user to input whatever information was relevant. The type of feedback will vary wildly depending on the church, the missionary, and many other variables. As long as the feedback was detailed, I could sort through it and make the changes necessary to each listing.

**Comment by amaster507** [comment]
A draft could be created with an API very quickly and easily without needing to have a publicly available form.

I want to use a user rating system for other users to help review the updates and upvote or downvote the suggested information. The updates will be very particular and reference exactly what information they are updating.

**Comment by MC1171611** [comment]
By form I meant within the app, not on the site. There's already a form on the site: https://www.kjvchurches.com/add-listing/?listing_type=gd_place

**Comment by amaster507** [comment]
closing this issue because I was asked to not link ifbmt to site data was scraped from.
