### ISSUE TITLE
Data Import

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#8]
# There should be a way to import existing user data.

Of course the easiest way to import data is from a CSV (excel) file and sanitizing the input and mapping the columns to the correct database fields. But, what other formats are data in that everyone is using that may need to be imported?

Automatic importing may not be available for every case and we may need to implement a process to submit files to be imported and then someone knowledgeable with the database structure can format, sanitize, and import the data.

Is this even something that is needed?

**Comment by hometeamsmissions** [comment]
I would think this is a definite necessity to attract users that have already started using a personal method.  File extensions for calendar imports like .ical and .ics come to mind.

**Comment by amaster507** [comment]
For Documentation purposes: Google calendars can be exported as .ics file. Below is an example of one event off from my church calendar:

```
BEGIN:VEVENT
DTSTART;TZID=America/Chicago:20111218T104500
DTEND;TZID=America/Chicago:20111218T121500
RRULE:FREQ=WEEKLY;BYDAY=SU
DTSTAMP:20170903T201611Z
UID:l28pl7e9rhecpb4tunf9rrggq4@google.com
CLASS:PUBLIC
CREATED:20111221T035351Z
DESCRIPTION:Pastor George Theroux preaches from the Bible with the message 
 that God has laid upon his heart\, while the Masters and Mrs. Theroux have 
 fun with the kids playing games and learning Bible stories on their level.
LAST-MODIFIED:20111221T041046Z
LOCATION:Cornerstone Baptist Church\, Mcalester\, OK
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:Sunday Morning Worship Service and Jr. Church
TRANSP:OPAQUE
END:VEVENT
```

The important parts to import are: `DSTART`, `DTEND`, `RRULE` (Recurring Rule), `DESCRIPTION`, `LOCATION`, and `SUMMARY`

I will start a new issue having said this, is there a need for recurring events #11.

**Comment by rmurray525** [comment]
Personally, I would think syncing both ways would be good. 
So, if I add a meeting in the app, could it show up in my calendar (apple user) but if I make an event in the calendar, have the option of it being added to my calendar?
This way, it shows up on my phone, iPad, computer, etc...no matter if it has the app or not.

**Comment by amaster507** [comment]
for my review and research on such capabilities: [is-there-any-open-icalender-api](https://stackoverflow.com/questions/6595683/is-there-any-open-icalender-api)

**Comment by amaster507** [comment]
I have opened a new issue #20 Syncing Calendars to iCloud calendar or other iCalendar related apps.

**Comment by amaster507** [comment]
added to roadmap: https://trello.com/c/VBKTt2CF/13-importing-data
