### ISSUE TITLE
Schedule Booking Confirmation

### ISSUE THREAD

**Issue by amaster507** [amaster507/ifbmt#9]
When booking an appointment, there needs to be a process to send confirmation to the email address on file or an updated email if provided.

This confirmation should send to the contact at the church and Carbon Copy the missionary for record keeping and confirmation.

**Comment by johntink1088** [comment]
Maybe even a template where the only thing changing for letter to letter would be church name and date of meeting.   (With option to add note or edit.)

**Comment by amaster507** [comment]
Good idea for adding template with ability to edit before sending our attaching a note.
